POST   http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVscHJ1ZWJhcyIsImlkIjoiNjgyZGM5NGNhOTY2MzMzY2MyOTg4NGY4IiwiaWF0IjoxNzQ3ODMxMTQwLCJleHAiOjE3NDc4MzQ3NDB9.nMSzfEBafZnHmjwuTyewCcRC9FqRl-5Fooby9uJJgYQ

{
  "title": "pruebas variadas",
  "author": "El Pruebas",
  "url": "pruebas.com",
  "likes": 181,
  "userId": "682dc94ca966333cc29884f8"
}

